version: "3"

volumes:
  pgdata: {}
  esdata: {}

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  es:
    image: elasticsearch:7.7.0
    container_name: es
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  dj:
    container_name: dj
    build: django
    env_file:
      - .env
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - es
    command: /start.sh
    #command: python manage.py runserver 0.0.0.0:80