# Generated by Django 3.0.6 on 2020-05-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('displaySymbol', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finhub.Exchange')),
            ],
        ),
    ]
